# Generated by Django 5.0 on 2024-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_prj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('quantity', models.CharField(max_length=50, verbose_name='Количество')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
